package org.pinnaclesmp.fragguard;

import org.bukkit.Material;
import org.bukkit.Server;
import org.bukkit.World;
import org.bukkit.configuration.file.YamlConfiguration;
import org.bukkit.plugin.java.JavaPlugin;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Base64;
import java.util.List;
import java.util.UUID;
import java.util.logging.Logger;
import java.util.zip.GZIPInputStream;
import java.util.zip.GZIPOutputStream;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Regression fixtures for history produced by FragGuard 26.2-1.1.2 / Paper 26.2 build 121.
 *
 * <p>The block-entity envelope is format version 1 in both the 26.2 release and the 26.3
 * development line. The item-array payload below was generated by the actual 26.2 release JAR
 * running on Paper 26.2 build 121, rather than by the current Paper API.</p>
 */
class Paper262PersistenceCompatibilityTest {
    private static final UUID WORLD_UUID = UUID.fromString("563fce36-6445-43e9-9e79-3bb6d0780b13");
    private static final UUID ACTOR_UUID = UUID.fromString("714ea63f-075e-4694-b2c4-ae06a79748aa");
    private static final byte[] PAPER_262_ITEM_ARRAY = Base64.getDecoder().decode(
            "AQAAAAMAAABMH4sIAAAAAAAA/+NiYGBm4HZJLEkMSy0qzszPY2AQVudgYMpMYRDMzcxLTS5KTCuxSslMzM3PS2FmYE3OL80rYQBpAgAFZtm1OgAAAAAAAAAAAABPH4sIAAAAAAAA/+NiYGBm4HZJLEkMSy0qzszPY2AQVudgYMpMYRDKzcxLTS5KTCuxyk/Mji/OTM9jZmBNzi/NK2FgYGBiAABEjV0KOwAAAA==");

    @TempDir
    Path temporaryDirectory;

    private Database database;

    @AfterEach
    void shutDownDatabase() {
        if (database != null) {
            database.shutdown();
        }
    }

    @Test
    void migratesVersionThreeHistoryWithoutRewritingLegacySnapshotsOrRollbackJobs() throws Exception {
        byte[] legacyContainer = inventorySnapshot("Legacy chest");
        long now = System.currentTimeMillis();

        database = startDatabase();
        database.insertRequiredAsync(List.of(
                new BlockChange(now - 2_000L, ACTOR_UUID.toString(), "Builder", "world",
                        1, 64, 1, ChangeAction.BREAK, "minecraft:stone", "minecraft:air"),
                new BlockChange(now - 1_000L, ACTOR_UUID.toString(), "Builder", "world",
                        2, 64, 2, ChangeAction.BREAK, "minecraft:chest", "minecraft:air",
                        legacyContainer, null)
        )).join();

        RollbackJob job = database.createRollbackJobAsync(ACTOR_UUID.toString(), "Builder", "world",
                2, 2, 3, now - 3_000L, now, false,
                List.of(new RollbackTarget("world", 2, 64, 2,
                        "minecraft:chest", "minecraft:air", legacyContainer, null))).join();
        RollbackJobChange change = database.loadRollbackChangesAsync(job.id(), false).join().get(0);
        database.prepareRollbackBatchAsync(job.id(),
                List.of(change.withBeforeState("minecraft:air", null))).join();
        database.markRollbackBatchAppliedAsync(job.id(),
                List.of(new RollbackStepResult(change.sequence(), true, false,
                        "minecraft:chest", legacyContainer))).join();
        database.completeRollbackJobAsync(job.id(), false).join();
        database.shutdown();
        database = null;

        // Schema v3 was the schema shipped by 26.2-1.1.2. Version 4 only removes this index.
        try (Connection connection = openDatabase(); Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                    CREATE UNIQUE INDEX IF NOT EXISTS idx_fg_tick_coalesce
                    ON block_changes(world_uuid, x, y, z, coalesce_session, server_tick)
                    """);
            statement.execute("PRAGMA user_version=3");
        }

        database = startDatabase();

        try (Connection connection = openDatabase(); Statement statement = connection.createStatement()) {
            try (ResultSet version = statement.executeQuery("PRAGMA user_version")) {
                assertTrue(version.next());
                assertEquals(Database.SCHEMA_VERSION, version.getInt(1));
            }
            try (ResultSet index = statement.executeQuery("""
                    SELECT COUNT(*) FROM sqlite_master
                    WHERE type='index' AND name='idx_fg_tick_coalesce'
                    """)) {
                assertTrue(index.next());
                assertEquals(0, index.getInt(1), "v3 -> v4 should only remove the obsolete coalescing index");
            }
            try (ResultSet history = statement.executeQuery("""
                    SELECT before_entity_data FROM block_changes
                    WHERE x=2 AND y=64 AND z=2
                    """)) {
                assertTrue(history.next());
                assertArrayEquals(legacyContainer, history.getBytes(1),
                        "migration must not rewrite historical block-entity snapshots");
            }
            try (ResultSet savedJob = statement.executeQuery("""
                    SELECT target_entity_data, applied_entity_data
                    FROM rollback_job_changes WHERE job_id=""" + job.id())) {
                assertTrue(savedJob.next());
                assertArrayEquals(legacyContainer, savedJob.getBytes("target_entity_data"));
                assertArrayEquals(legacyContainer, savedJob.getBytes("applied_entity_data"));
            }
        }

        LookupPage lookup = database.lookupAsync("world", 1, 1, 5, 1, 20, 30).join();
        assertEquals(2, lookup.totalRows());
        LookupRow chestHistory = lookup.rows().stream()
                .filter(row -> row.x() == 2 && row.y() == 64 && row.z() == 2)
                .findFirst().orElseThrow();
        assertArrayEquals(legacyContainer, chestHistory.beforeEntityData());

        List<RollbackTarget> preview = database.rollbackTargetsAsync(
                "world", 2, 2, 2, now - 3_000L, now, 20).join();
        RollbackTarget chestTarget = preview.stream()
                .filter(target -> target.x() == 2 && target.y() == 64 && target.z() == 2)
                .findFirst().orElseThrow();
        assertArrayEquals(legacyContainer, chestTarget.targetEntityData(),
                "a 26.2 history row must remain usable as a 26.3 rollback preview target");

        assertTrue(FragGuardCommand.matchesState(
                "minecraft:chest", legacyContainer,
                "minecraft:chest", legacyContainer.clone()));
        assertFalse(FragGuardCommand.matchesState(
                "minecraft:chest", legacyContainer,
                "minecraft:chest", null),
                "missing legacy persistent state must remain fail-closed rather than becoming a wildcard");

        RollbackJob undoing = database.beginUndoAsync(job.id()).join();
        assertEquals("UNDOING", undoing.status());
        List<RollbackJobChange> undo = database.loadRollbackChangesAsync(job.id(), true).join();
        assertEquals(1, undo.size());
        assertArrayEquals(legacyContainer, undo.get(0).targetEntityData());
        assertArrayEquals(legacyContainer, undo.get(0).appliedEntityData());
        database.markUndoBatchAppliedAsync(job.id(),
                List.of(new RollbackStepResult(undo.get(0).sequence(), true, false))).join();
        assertEquals("UNDONE", database.completeRollbackJobAsync(job.id(), true).join().status());
    }

    @Test
    void readsNonInventoryVersionOneBlockEntityKindsWrittenByThe26_2Release() throws Exception {
        BlockEntitySnapshot.SnapshotDescription sign = BlockEntitySnapshot.describe(signSnapshot());
        assertTrue(sign.readable());
        assertEquals("Sign", sign.type());
        assertTrue(sign.details().stream().anyMatch(detail -> detail.contains("Front legacy")));

        BlockEntitySnapshot.SnapshotDescription banner = BlockEntitySnapshot.describe(bannerSnapshot());
        assertTrue(banner.readable());
        assertEquals("Banner", banner.type());
        assertTrue(banner.details().stream().anyMatch(detail -> detail.contains("Stripe Downright")));

        BlockEntitySnapshot.SnapshotDescription skull = BlockEntitySnapshot.describe(skullSnapshot());
        assertTrue(skull.readable());
        assertEquals("Player head", skull.type());
        assertTrue(skull.details().stream().anyMatch(detail -> detail.contains("LegacyBuilder")));
    }

    @Test
    void preservesExactPaper26_2ItemBytesInContainerLecternAndPotEnvelopes() throws Exception {
        byte[] inventory = inventorySnapshot("Legacy chest");
        assertEquals("{\"text\":\"Legacy chest\"}", extractCustomName(inventory));
        assertArrayEquals(PAPER_262_ITEM_ARRAY, extractInventoryPayload(inventory, "INVENTORY"));
        assertArrayEquals(PAPER_262_ITEM_ARRAY, extractInventoryPayload(lecternSnapshot(), "LECTERN"));
        assertArrayEquals(PAPER_262_ITEM_ARRAY, extractInventoryPayload(decoratedPotSnapshot(), "DECORATED_POT"));
    }

    private Database startDatabase() throws Exception {
        JavaPlugin plugin = mock(JavaPlugin.class);
        Server server = mock(Server.class);
        World world = mock(World.class);
        YamlConfiguration configuration = new YamlConfiguration();
        configuration.set("database-write-queue-capacity", 64);
        configuration.set("database-write-batch-size", 16);
        configuration.set("database-query-timeout-seconds", 5);
        when(plugin.getDataFolder()).thenReturn(temporaryDirectory.toFile());
        when(plugin.getConfig()).thenReturn(configuration);
        when(plugin.getServer()).thenReturn(server);
        when(plugin.getLogger()).thenReturn(Logger.getLogger("Paper262PersistenceCompatibilityTest"));
        when(server.getCurrentTick()).thenReturn(100);
        when(server.getWorld("world")).thenReturn(world);
        when(server.getWorlds()).thenReturn(List.of(world));
        when(world.getUID()).thenReturn(WORLD_UUID);
        when(world.getName()).thenReturn("world");

        Database instance = new Database(plugin);
        instance.init();
        return instance;
    }

    private Connection openDatabase() throws Exception {
        Class.forName("org.sqlite.JDBC");
        return DriverManager.getConnection("jdbc:sqlite:" + temporaryDirectory.resolve("fragguard.db"));
    }

    private byte[] inventorySnapshot(String customName) throws IOException {
        return snapshot("INVENTORY", customName == null ? null : "{\"text\":\"" + customName + "\"}",
                output -> writeInventory(output, PAPER_262_ITEM_ARRAY));
    }

    private byte[] lecternSnapshot() throws IOException {
        return snapshot("LECTERN", null, output -> {
            writeInventory(output, PAPER_262_ITEM_ARRAY);
            output.writeInt(7);
        });
    }

    private byte[] decoratedPotSnapshot() throws IOException {
        return snapshot("DECORATED_POT", null, output -> {
            writeInventory(output, PAPER_262_ITEM_ARRAY);
            org.bukkit.block.DecoratedPot.Side[] sides = org.bukkit.block.DecoratedPot.Side.values();
            output.writeInt(sides.length);
            for (org.bukkit.block.DecoratedPot.Side side : sides) {
                output.writeUTF(side.name());
                output.writeUTF(Material.BRICK.name());
            }
        });
    }

    private byte[] signSnapshot() throws IOException {
        return snapshot("SIGN", null, output -> {
            output.writeBoolean(true);
            writeSignSide(output, "RED", true, "Front legacy", "", "", "");
            writeSignSide(output, "BLUE", false, "Back legacy", "", "", "");
        });
    }

    private byte[] bannerSnapshot() throws IOException {
        return snapshot("BANNER", null, output -> {
            output.writeInt(1);
            output.writeUTF("RED");
            output.writeUTF("minecraft:stripe_downright");
        });
    }

    private byte[] skullSnapshot() throws IOException {
        return snapshot("SKULL", null, output -> {
            output.writeBoolean(true);
            writeNullable(output, "563fce36-6445-43e9-9e79-3bb6d0780b13");
            writeNullable(output, "LegacyBuilder");
            output.writeInt(1);
            output.writeUTF("textures");
            output.writeUTF("legacy-texture-value");
            writeNullable(output, "legacy-signature");
        });
    }

    private byte[] snapshot(String kind, String customNameJson, SnapshotWriter writer) throws IOException {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        try (DataOutputStream output = new DataOutputStream(new GZIPOutputStream(bytes))) {
            output.writeInt(0x46474245);
            output.writeByte(1);
            output.writeUTF(kind);
            writeNullable(output, customNameJson);
            writer.write(output);
        }
        return bytes.toByteArray();
    }

    private void writeInventory(DataOutputStream output, byte[] payload) throws IOException {
        output.writeInt(payload.length);
        output.write(payload);
    }

    private void writeSignSide(DataOutputStream output, String color, boolean glowing,
                               String... lines) throws IOException {
        output.writeUTF(color);
        output.writeBoolean(glowing);
        output.writeInt(lines.length);
        for (String line : lines) {
            writeNullable(output, "{\"text\":\"" + line + "\"}");
        }
    }

    private void writeNullable(DataOutputStream output, String value) throws IOException {
        output.writeBoolean(value != null);
        if (value != null) {
            output.writeUTF(value);
        }
    }

    private String extractCustomName(byte[] snapshot) throws IOException {
        try (DataInputStream input = openSnapshot(snapshot)) {
            readHeader(input, "INVENTORY");
            return input.readBoolean() ? input.readUTF() : null;
        }
    }

    private byte[] extractInventoryPayload(byte[] snapshot, String expectedKind) throws IOException {
        try (DataInputStream input = openSnapshot(snapshot)) {
            readHeader(input, expectedKind);
            if (input.readBoolean()) {
                input.readUTF();
            }
            int length = input.readInt();
            byte[] payload = input.readNBytes(length);
            assertEquals(length, payload.length);
            return payload;
        }
    }

    private DataInputStream openSnapshot(byte[] snapshot) throws IOException {
        return new DataInputStream(new GZIPInputStream(new ByteArrayInputStream(snapshot)));
    }

    private void readHeader(DataInputStream input, String expectedKind) throws IOException {
        assertEquals(0x46474245, input.readInt());
        assertEquals(1, input.readUnsignedByte());
        assertEquals(expectedKind, input.readUTF());
    }

    @FunctionalInterface
    private interface SnapshotWriter {
        void write(DataOutputStream output) throws IOException;
    }
}
